"""added unqiue on albums

Revision ID: 0b4007d3e616
Revises: f35443ac34d9
Create Date: 2025-07-02 02:10:55.631037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b4007d3e616'
down_revision: Union[str, None] = 'f35443ac34d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_name_author_id', 'albums', ['name', 'author_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_name_author_id', 'albums', type_='unique')
    # ### end Alembic commands ###
