"""added on delete on albums

Revision ID: 51d5fe4c7ae4
Revises: 0b4007d3e616
Create Date: 2025-07-02 02:15:55.753980

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51d5fe4c7ae4'
down_revision: Union[str, None] = '0b4007d3e616'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('albums_genres_association_table_album_id_fkey'), 'albums_genres_association_table', type_='foreignkey')
    op.drop_constraint(op.f('albums_genres_association_table_genre_id_fkey'), 'albums_genres_association_table', type_='foreignkey')
    op.create_foreign_key(None, 'albums_genres_association_table', 'genres', ['genre_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'albums_genres_association_table', 'albums', ['album_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'albums_genres_association_table', type_='foreignkey')
    op.drop_constraint(None, 'albums_genres_association_table', type_='foreignkey')
    op.create_foreign_key(op.f('albums_genres_association_table_genre_id_fkey'), 'albums_genres_association_table', 'genres', ['genre_id'], ['id'])
    op.create_foreign_key(op.f('albums_genres_association_table_album_id_fkey'), 'albums_genres_association_table', 'albums', ['album_id'], ['id'])
    # ### end Alembic commands ###
