"""added on delete on albums

Revision ID: a854bd39d775
Revises: 51d5fe4c7ae4
Create Date: 2025-07-02 02:16:21.229729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a854bd39d775'
down_revision: Union[str, None] = '51d5fe4c7ae4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('albums_artists_association_table_artist_id_fkey'), 'albums_artists_association_table', type_='foreignkey')
    op.drop_constraint(op.f('albums_artists_association_table_album_id_fkey'), 'albums_artists_association_table', type_='foreignkey')
    op.create_foreign_key(None, 'albums_artists_association_table', 'albums', ['album_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'albums_artists_association_table', 'artists', ['artist_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'albums_artists_association_table', type_='foreignkey')
    op.drop_constraint(None, 'albums_artists_association_table', type_='foreignkey')
    op.create_foreign_key(op.f('albums_artists_association_table_album_id_fkey'), 'albums_artists_association_table', 'albums', ['album_id'], ['id'])
    op.create_foreign_key(op.f('albums_artists_association_table_artist_id_fkey'), 'albums_artists_association_table', 'artists', ['artist_id'], ['id'])
    # ### end Alembic commands ###
