"""added fk for songs to users

Revision ID: e3ac370fdee8
Revises: 3b76a8763dff
Create Date: 2025-04-12 23:06:12.534923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3ac370fdee8'
down_revision: Union[str, None] = '3b76a8763dff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('songs', sa.Column('author_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'songs', 'users', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'songs', type_='foreignkey')
    op.drop_column('songs', 'author_id')
    # ### end Alembic commands ###
