"""refactored albums logic

Revision ID: f0a4663f8f69
Revises: 7a684572e8bf
Create Date: 2025-07-02 01:12:47.852908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0a4663f8f69'
down_revision: Union[str, None] = '7a684572e8bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('albums_songs_association_table')
    op.create_foreign_key(None, 'albums', 'users', ['author_id'], ['id'])
    op.add_column('songs', sa.Column('is_published', sa.Boolean(), nullable=False, server_default="false"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('songs', 'is_published')
    op.drop_constraint(None, 'albums', type_='foreignkey')
    op.create_table('albums_songs_association_table',
    sa.Column('album_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('song_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], name=op.f('albums_songs_association_table_album_id_fkey')),
    sa.ForeignKeyConstraint(['song_id'], ['songs.id'], name=op.f('albums_songs_association_table_song_id_fkey')),
    sa.PrimaryKeyConstraint('album_id', 'song_id', name=op.f('albums_songs_association_table_pkey'))
    )
    # ### end Alembic commands ###
