"""added on cascade delete

Revision ID: f35443ac34d9
Revises: f0a4663f8f69
Create Date: 2025-07-02 01:28:40.613455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f35443ac34d9'
down_revision: Union[str, None] = 'f0a4663f8f69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playlist_artists_association_table')
    op.drop_constraint(op.f('subscriptions_user_id_fkey'), 'subscriptions', type_='foreignkey')
    op.drop_column('subscriptions', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('subscriptions_user_id_fkey'), 'subscriptions', 'users', ['user_id'], ['id'])
    op.create_table('playlist_artists_association_table',
    sa.Column('playlist_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], name=op.f('playlist_artists_association_table_artist_id_fkey')),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlist.id'], name=op.f('playlist_artists_association_table_playlist_id_fkey')),
    sa.PrimaryKeyConstraint('playlist_id', 'artist_id', name=op.f('playlist_artists_association_table_pkey'))
    )
    # ### end Alembic commands ###
