"""added payment method to sub

Revision ID: fb4dab541081
Revises: 3f149f24390c
Create Date: 2025-05-04 21:48:04.165693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb4dab541081'
down_revision: Union[str, None] = '3f149f24390c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('payment_method', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'subscriptions', 'payment_choices', ['payment_method'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.drop_column('subscriptions', 'payment_method')
    # ### end Alembic commands ###
