from enum import Enum

class Grants(str, Enum):
    CAN_LISTEN = "CAN_LISTEN"
    CAN_CREATE_PLAYLIST = "CAN_CREATE_PLAYLIST"
    CAN_DOWNLOAD_SONGS = "CAN_DOWNLOAD_SONGS"
    CAN_SKIP_ADS = "CAN_SKIP_ADS"

    CAN_ACCESS_PREMIUM_FEATURES = "CAN_ACCESS_PREMIUM_FEATURES"
